name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: ビルド環境のセットアップ
      run: sudo ./setup_machine.sh
    - name: rootfsのビルド
      run: ./build.sh
    - name: rootfs.tar.gz が作成されたか確認する
      run: test -f ./build/rootfs.tar.gz
